# Generated by Django 6.0.3 on 2026-03-25 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('id_card', models.FileField(blank=True, null=True, upload_to='student_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
