# Generated by Django 6.0.3 on 2026-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('questionbank', '0002_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='questions',
            field=models.ManyToManyField(to='questionbank.question'),
        ),
    ]
