# Generated by Django 6.0.3 on 2026-03-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examattempt_questions'),
        ('questionbank', '0002_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questionbank.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionbank.questionbank'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
