# Generated by Django 6.0.3 on 2026-03-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_duration_exam_is_published_exam_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
    ]
